import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Urbanist, Inter_Tight } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar";

// fonts: Mulish, Open_Sans, Outfit,

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}

const montserrat = Urbanist({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-montserrat"
})

const openSans = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-open-sans"
})

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${openSans.variable} antialiased font-Montserrat`}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
