import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Urbanist, Inter_Tight } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/navbar";
import { currentUser } from "@/lib/db/queries/user";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth";

// fonts: Mulish, Open_Sans, Outfit,

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}

const montserrat = Urbanist({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-montserrat"
})

const openSans = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-open-sans"
})

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {
  const signedInuser = await currentUser()
  const session = await auth()
  
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`${montserrat.variable} ${openSans.variable} antialiased font-Montserrat`}>
          <Navbar signedInuser={signedInuser}/>
          {children}
          <Toaster position="top-center" theme="light" richColors className="font-Montserrat"/>
        </body>
      </SessionProvider>
    </html>
  );
}
